repos:
  # Basic pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: mixed-line-ending
        args: ['--fix=lf']

  # Black code formatting
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=88]

  # Import sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

  # Flake8 linting
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=88, --extend-ignore=E203,W503,E501]
        additional_dependencies:
          - flake8-docstrings
          - flake8-import-order
          - flake8-bugbear

  # Type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
      - id: mypy
        additional_dependencies: [types-all]
        args: [--ignore-missing-imports, --scripts-are-modules]
        exclude: ^(docs/|experimental-data/|tests/fixtures/)

  # Security scanning
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]
        exclude: ^tests/

  # Upgrade syntax for newer Python versions
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.7.0
    hooks:
      - id: pyupgrade
        args: [--py38-plus]

  # Remove unused imports
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.1.1
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --remove-unused-variables
          - --remove-duplicate-keys
          - --ignore-init-module-imports

  # Scientific Python specific checks
  - repo: https://github.com/numpy/numpydoc
    rev: v1.5.0
    hooks:
      - id: numpydoc-validation
        exclude: ^(tests/|docs/|experimental-data/)

  # YAML formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.9-for-vscode
    hooks:
      - id: prettier
        types: [yaml]
        additional_dependencies:
          - prettier@2.8.8

  # Markdown formatting and linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.35.0
    hooks:
      - id: markdownlint
        args: [--fix]

  # Check for common mistakes in Python
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-no-log-warn
      - id: python-use-type-annotations
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal

  # Local hooks for project-specific checks
  - repo: local
    hooks:
      - id: oscillatory-framework-validation
        name: Validate Oscillatory Framework Implementation
        entry: python -m scripts.validate_oscillatory_framework
        language: system
        files: ^src/.*\.py$
        pass_filenames: false

      - id: cardiovascular-analysis-tests
        name: Run Cardiovascular Analysis Unit Tests
        entry: pytest tests/unit/ -v
        language: system
        files: ^src/cardiovascular.*\.py$
        pass_filenames: false

      - id: check-scientific-citations
        name: Check Scientific Citation Format
        entry: python -m scripts.check_citations
        language: system
        files: \.(py|md|rst)$
        pass_filenames: true

      - id: validate-data-schemas
        name: Validate Data Schema Compliance
        entry: python -m scripts.validate_data_schemas
        language: system
        files: ^(src/|demo/).*\.py$
        pass_filenames: false

# Configuration for specific hooks
default_language_version:
  python: python3.8

# Global excludes
exclude: |
  (?x)^(
      \.git/.*|
      \.tox/.*|
      \.venv/.*|
      venv/.*|
      build/.*|
      dist/.*|
      \.eggs/.*|
      experimental-data/.*|
      docs/_build/.*
  )$

# CI configuration
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false
